### ISSUE TITLE
Binstar build overwrites the previous builds (combinations of python and numpy versions)

### ISSUE THREAD

**Issue by chdoig** [ContinuumIO/into#113]
@mrocklin, I was trying to get a new version for python 2.7 in binstar, as instructed by doing:

```
conda install -c blaze into -f
```
and I was still getting my previous error:
```
    /Users/cdoig/anaconda/envs/topik/lib/python2.7/site-packages/into/convert.pyc in series_to_array(s, dshape, **kwargs)
         66 @convert.register(np.ndarray, pd.Series, cost=0.1)
         67 def series_to_array(s, dshape=None, **kwargs):
    ---> 68     dtype = datashape.to_numpy_dtype(datashape.dshape(dshape))
         69     sdtype = s.dtype
         70     values = s.values
```
I then checked binstar and wasn't able to find a new package for 2.7. I was just seeing this package info:
```
depends	[u'datashape', u'multipledispatch', u'networkx', u'numpy 1.9*', u'pandas', u'python 3.4*', u'toolz']
```
I then discovered that binstar was creating the same name for all versions:

```
586[warning] Distribution osx-64/into-0.2.2-8_g68222bc.tar.bz2 already exists ... removing 
587Exit BINSTAR_BUILD_RESULT=success
```
and it was removing the previous built package (with different python and numpy versions):
e.g.:
https://binstar.org/blaze/into/builds/85/9#log
https://binstar.org/blaze/into/builds/85/8#log

and that the one that remained was the latest:
https://binstar.org/blaze/into/builds/85/11, with numpy=1.9 and python=3.4

I've opened a PR #112 to add the python version to the string, like @tswicegood does in conda-env:
https://github.com/conda/conda-env/blob/develop/conda.recipe/meta.yaml

But still haven't figured out how to include the numpy version.

**Comment by chdoig** [comment]
I just found in the conda docs that
http://conda.pydata.org/docs/build.html#environment-variables-that-affect-the-build-process

there are this environment variables:
```
Environment variables that affect the build process
CONDA_PY	Should be 26, 27, 33, or 34. This is the Python version used to build the package.
CONDA_NPY	Should be either 16 or 17. This is the NumPy version used to build the package.
```
So, I guess we can use CONDA_NPY and add it to the string.

Not sure if we should use CONDA_PY instead of @tswicegood's PY_VER.

**Comment by mrocklin** [comment]
I'm very glad to have other people checking over the conda recipe.  I'm pretty ignorant here.

**Comment by mrocklin** [comment]
Should the solution as written in master work?  cc @asmeurer

**Comment by mrocklin** [comment]
Given my ignorance with conda I'm somewhat hesitant to keep adding little tricks into the recipe.  The `into` case is pretty simple (or should be) and so the naive solution from the docs should ideally work.  If not it might be necessary to change the conda-docs or report errors upstream.

**Comment by chdoig** [comment]
@mrocklin, I agree with you that a simple case should have a simple solution. I also don't like the proposed change in the PR #112, but I haven't found many projects that use binstar build or a place where a standard is defined for setting a build string when using binstar build.

In the docs, the meta.yaml says that the 'string' defaults to the default conda build string plus the build number: http://conda.pydata.org/docs/build.html#the-meta-yaml-file

```
build:
  # The build number should be incremented for new builds of the same version
  number: 1       # (defaults to 0)
  string: abc     # (defaults to default conda build string plus the build
                  # number)
                  # The build string cannot contain a dash '-' character
```

In a subsection, it mentions that if you set the environment to the GIT_BUILD_STR, that will override the default build string with the python and numpy version:
http://conda.pydata.org/docs/build.html#git-environment-variables

```
# Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}
```

When you simplified the recipe in this commit:
https://github.com/ContinuumIO/into/commit/e4f1bb66f64c3a3901d54b69055e53848924e590
you changed how your packages are named and packages with different python and numpy dependencies don't have a different name.

e.g: from into-0.1.4.post080.g4254125-np19py27_0.tar.bz2 to  into-0.2.2-8_g68222bc.tar.bz2.

I think ``string: {{ environ.get('GIT_BUILD_STR', '') }}`` is a bad example to have in the docs, because the build string is supposed to "identify a particular build of a package for conda" http://conda.pydata.org/docs/intro.html#package-naming-conventions and the GIT_BUILD_STR doesn't uniquely identify a build, it identifies a commit:

```
GIT_DESCRIBE_TAG	string denoting the most recent tag from the current commit (based on the output of git describe --tags)
GIT_DESCRIBE_NUMBER	string denoting the number of commits since the most recent tag
GIT_DESCRIBE_HASH	the current commit short-hash as displayed from git describe --tags
GIT_BUILD_STR	a string that joins GIT_DESCRIBE_NUMBER and GIT_DESCRIBE_HASH by an underscore.
```

If you don't care about having a git identifier, a simple solution that solves the problem is to use the conda default build string and just remove the line, like in the meta.yaml in Anaconda:
https://github.com/ContinuumIO/anaconda/blob/master/packages/into-0.2.2/meta.yaml

You're right that changes should be made upstream and that the example in the docs should be changed. I'll also add that there should be a better environment variable that contained the CONDA_PY, CONDA_NPY and GIT_BUILD_STR to uniquely identify a build. I'll open issues in conda to discuss them.
