### ISSUE TITLE
Converting from SQL to recarray results in array

### ISSUE THREAD

**Issue by FRidh** [ContinuumIO/into#24]
Converting from SQL (SQLite) to a `recarray` results in a normal array. Converting from CSV to `recarray` works fine.

```py
In [9]: rcv = into(np.recarray, FILE_RECEIVERS)
In [10]: type(rcv)
Out[10]: numpy.core.records.recarray
In [11]: rcv = into(np.recarray, TABLE_RECEIVERS)
In [12]: type(rcv)
Out[12]: numpy.ndarray
```
Could this be due to `cost=0.0` for `np.array` to `np.recarray`?
Converting first into `DataFrame` and then into `recarray` works.

**Comment by mrocklin** [comment]
Yup, that's an issue.  Fixed in https://github.com/ContinuumIO/into/pull/25 I think.
