### ISSUE TITLE
AWS <-> AWS

### ISSUE THREAD

**Issue by cpcloud** [ContinuumIO/into#34]
From a private conversation:

Would be nice if `into` could move files in S3 to e.g., Redshift

```
data = into('redshift://conn_info::table', 's3://my/s3/bucket/*.csv')
```

**Comment by mrocklin** [comment]
There are presumably a few things in AWS world.  I can imagine a separate connected component in the into graph to manage these similar to how we might handle HDFS (#29).  

My current thoughts on this is that we resort to metaclassing as we did with `Chunks` and have types `S3(CSV)`, `S3(JSON)`, etc. as well as standard `sqlalchemy.Table` for things like redshift.

A good first step would be to make functions like `discover(S3(CSV))` that perhaps downloaded a small sample of a file, then called `discover` locally.  

I don't think any of this is hard from an `into/blaze` perspective.  I think that most of the work here is just becoming familiar with the AWS technology stack.

**Comment by cpcloud** [comment]
for reference:

https://github.com/binarydud/redshift_sqlalchemy

**Comment by cpcloud** [comment]
redshift can only take data from s3 or dynamo

http://docs.aws.amazon.com/redshift/latest/dg/t_Loading_data.html

**Comment by cpcloud** [comment]
that doesn't limit us necessarily, except that ultimately to get something into redshift you have to through one of those things first

**Comment by mrocklin** [comment]
If only we had some mechanism to chain a sequence of conversions through a complex network...

**Comment by cpcloud** [comment]
:)

**Comment by mrocklin** [comment]
I think that @TomAugspurger and @wrobstory may have some experience with the AWS stack.  This might interest them.

**Comment by wrobstory** [comment]
oh hi

So I've written a very small library to perform the Postgres -> Redshift data shuffle : https://github.com/wrobstory/pgshift

The pipeline looks like pg_dump -> Pandas DataFrame -> S3 -> Redshift, with some gzipping + chunking to take advantage of Redshift's parallel-ity to improve load/COPY times. So, that code is probably a good starting point for something like `into('postgres://conn_info::table', 'redshift://conn_info::table')`, `into(DataFrame, 'redshift://conn_info::table')`, and `into('s3://my/s3/bucket/*.csv', 'redshift://conn_info::table')`

For data already in S3, I have a tool that will [reconcile S3 keys to those that have already been loaded in Redshift](https://github.com/wrobstory/reconciler), which could also be useful. 

Let me get my head around whats happening in this library- at first glance it looks like I should be able to wrap my code with your `@convert` decorator and get this done pretty quickly.

**Comment by mrocklin** [comment]
For wrapping one's head around `into` I've also been creating this tutorial which might be worth skimming.

https://github.com/mrocklin/blaze-tutorial

**Comment by TomAugspurger** [comment]
Not much to add to what Rob said.

I haven't looked closely at the `into` library, but if you have two routes to a target, is there any kind of cost calculation to choose the faster route? It's *so* much faster to create a table in redshift via s3 and a `copy` than a straight `df.to_sql`.

**Comment by mrocklin** [comment]
Yes, `convert` edges/functions can be annotated with a cost.  We use networkx to find minimum length paths.

**Comment by TomAugspurger** [comment]
Great. The only other thing I'd add is that pandas has an open issue to support writing DataFrames to s3 URIs (we support reading right now). I've been lazy and have just used Rob's pgshift, since I only ever write to s3 to go on to redshift. I can implement a DataFrame.to_csv with an s3 path if you think that'd be a useful edge for `into`.

**Comment by mrocklin** [comment]
@wrobstory how does your `Postgres -> Pandas -> RedShift` process compare to using insert statements through SQLAlchemy?  Presumably `into` would already be able to manage `Postgres -> Python tuples -> RedShift`.

I'm also excited by helping users interact with CSV or JSONLines data already on S3.  I would normally manage this by 

1.  Implementing `discover` on CSV files in S3 by downloading a small bit (can boto help with this?) and then calling `discover` on the local file.  This would give me a datashape
2.  SQLAlchemy + a datashape can probably already an empty table in Redshift with the right types
3.  Implementing a function to generate the right COPY command [like this one for postgres](https://github.com/ContinuumIO/into/blob/master/into/backends/sql_csv.py#L33-L55)

I'm not sure if this would work differently in AWS land though.

**Comment by mrocklin** [comment]
@TomAugspurger Rather than implement `DataFrame -> S3(CSV)` an alternative would be to implement `CSV -> S3(CSV)` and then use the existing `DataFrame -> CSV` route.

**Comment by mrocklin** [comment]
To be clear, when I mention the type `S3(CSV)` I'm using S3 as a sort of parametrized type.  This is the behavior that I have in mind

```Python
In [1]: from into import *
In [2]: run into/s3.py

In [3]: data = S3(CSV)('path/to/myfile.csv', delimiter=',')

In [4]: type(data)  # Parametrized type
Out[4]: S3(CSV)

In [5]: data.path  # Still a normal CSV file
Out[5]: 'path/to/myfile.csv'
```

Because `into` relies on the type of the data to choose which function we want to run, we need some way to differentiate between a local CSV file and one on S3 or one on HDFS, etc..  One approach is to make many subclasses `CSV_S3, CSV_HDFS, JSON_S3, ...` another approach is to construct these subclasses on the fly, as with this `S3` function.

```Python
from toolz import memoize

class _S3(object):
    pass

@memoize
def S3(cls):
    """ Parametrized S3 type """
    return type('S3(%s)' % cls.__name__, (cls, _S3), {'subtype': cls})
```

**Comment by cpcloud** [comment]
@wrobstory out of curiosity why is `gnureadline` a dep of `pgshift`?

**Comment by cpcloud** [comment]
@mrocklin i see, i sort of converged to something similar after playing around with the API a bit, but I like yours a bit better.

**Comment by wrobstory** [comment]
@cpcloud I'm not sure how that slipped in there- I did a pip freeze to a requirements file, and it's probably not actually needed. 

@mrocklin, the COPY should be much faster than a straight INSERT statement, but that's totally anecdotal; I haven't benchmarked one against the other. I do know that it's easy to get i/o bound on COPY statements from S3, so you definitely want to chunk + gzip if at all possible. 

I think steps 1 & 2 of your process for generating a COPY statement are what's missing in the pgshift code- right now you have to manually build the table yourself. Using a datashape to do that would be really great.

**Comment by cpcloud** [comment]
Looks like with a little effort it *is* possible to get only a small part of the file using a `Range` request header:

```python
import boto
from into import discover, CSV
import tempfile

conn = boto.connect_s3(anon=True)


def stream(uri):
    bucket, key = uri.split('/')
    resp = conn.make_request('GET', key=key,
                             bucket=bucket,
                             headers={'Content-Type': 'text/csv',
                                      'Range': 'bytes=0-3000'})
    with tempfile.NamedTemporaryFile(mode='w+b', delete=False) as f:
        raw = resp.read()
        f.write(raw[:raw.rfind('\n')])
        return CSV(f.name)


print(discover(stream('nyqpug/tips.csv')))
```

```sh
python s3stuff.py
```
gives

```python
var * {
  total_bill: float64,
  tip: float64,
  sex: string,
  smoker: string,
  day: string,
  time: string,
  size: int64
  }
```

**Comment by mrocklin** [comment]
That's awesome.  Next thing to check might be, will SQLAlchemy + resource successfully create a table for us on RedShift with that datashape?

**Comment by mrocklin** [comment]
@quasiben might know if Continuum has an aws account that one can use.

**Comment by TomAugspurger** [comment]
Just a quick, non-scientific benchmark. I made a 1000 x 4 DataFrame of floats and compared `df.to_sql`, which IIRC uses SQLAlchemy INSERTs by row, with a monkey-patched `df.to_redshift` method that goes df -> GZipped BytesIO -> s3 -> redshift.

`to_sql` took 2.5 minutes
`to_redshift` took 16 seconds.

My method doesn't do any chunking right now (maybe I'll try that later), so you could get even more of a speedup by loading chunks in parallel.

**Comment by mrocklin** [comment]
How does Redshift know how to interpret the bytes?

**Comment by cpcloud** [comment]
you have to tell it in the `COPY` command

**Comment by cpcloud** [comment]
i haven't added this yet, but i was going to do that tonight along with chunked uploading using multiprocessing

**Comment by cpcloud** [comment]
gzip is easy to add, it's simply an option in the `COPY` command, multipart uploads are not difficult but there are some details to straighten out

**Comment by mrocklin** [comment]
In the binary case what happens to things that don't have obvious standard binary representations, like datetimes?  Is Redshift expecting a certain format?

**Comment by cpcloud** [comment]
I'm not sure I understand, we'd have to go through CSV first. We couldn't just pipe a gzipped numpy array to redshift

**Comment by cpcloud** [comment]
it's quite liberal in the formats that it acceppts

**Comment by mrocklin** [comment]
Ah, sorry, my impression was that Tom was piping raw bytes to an S3 bucket and that Redshift had a way to interpret these raw bytes.

**Comment by cpcloud** [comment]
you can do neat things:

```python
In [36]: import gzip

In [37]: from cStringIO import StringIO

In [38]: sio = StringIO()

In [39]: with gzip.GzipFile(fileobj=sio, mode='wb') as f:
    df.to_csv(f)
    print(len(sio.getvalue()))
   ....:
10
```

**Comment by jseabold** [comment]
Does odo have support for redshift UNLOAD to an s3 prefix? I'm not seeing much in the way of this in the source at a glance.
