### ISSUE TITLE
Append sqlalchemy.Select to sqlalchemy.Table

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/into#36]
Sometimes we might want to do a computation and then keep the result in the database as another table.  To do this Blaze needs an `append(sqlalchemy.Table, sqlalchemy.Select)` implementation.  Presumably there is some way to generate an approprate `INSERT INTO ...` statement through sqlalchemy.

**Comment by cpcloud** [comment]
i can take this one:

for reference: http://docs.sqlalchemy.org/en/latest/core/tutorial.html#executing-multiple-statements
